### ISSUE TITLE
Image grid crashes the TUI

### ISSUE THREAD

**Issue by qrockz** [AnonymouX47/termvisage#10]
**Description**
```
termvisage --tui -r ~/Pictures -v
Using 'kitty' render style
Processing sources...
Checking '/home/t/Pictures'
... Done!
Session not ended successfully: (urwid.widget.widget.WidgetError) Widget <LineSquare selectable box widget <Image selectable box widget>> rendered (30 x 15) canvas when passed size (30, 1)!

termvisage --tui .
 File "/home/t/.local/pipx/venvs/termvisage/lib/python3.11/site-packages/urwid/widget/widget.py", line 92, in validate_size
    raise WidgetError(
urwid.widget.widget.WidgetError: Widget <LineSquare selectable box widget <Image selectable box widget>> rendered (30 x 15) canvas when passed size (30, 1)!
(797887) (2024-03-29 14:07:14,435) [CRITICAL] termvisage: Session not ended successfully: (urwid.widget.widget.WidgetError) Widget <LineSquare selectable box widge
```
**Desktop (please complete the following information, if applicable):**

- OS: Ubuntu 23.10
- Kernel version 6.5.0-26-generic

- Python version: Python 3.11.6
- Installation method: pipx install termvisage
```
termvisage --version 0.1.0
```
**Terminal Emulator:**

kitty 0.33.1

same Error on 
- konsole
- gnome-terminal
- wezterm

**Comment by AnonymouX47** [comment]
Thanks so much for the report.

I've started investigating the issue and it seems to be due to some fairly recent upstream changes in [urwid](https://github.com/urwid/urwid) (the TUI framework currently in use). The issue occurs starting from version 2.4.2.

In the mean time, you can downgrade `urwid` (within the same environment as `termvisage`) to version 2.1.2 using `pipx inject termvisage urwid==2.1.2`. Some newer versions should also work but I can't be sure other things aren't broken.

I'll continue to investigate till I get to the root of the issue and get back to you once I have something concrete.

Thanks once again. :pray:

**Comment by qrockz** [comment]
@AnonymouX47 
`
pipx inject termvisage urwid==2.1.2`

Kinda works so far :+1: . 

The only issue I have now is that one particular picture is not drawn in the preview. If I select it and termvisage goes fullscreen mode it is also not drawn. When I force it to draw it is finally drawn.
![grid](https://github.com/AnonymouX47/termvisage/assets/56853194/1cfcdc75-10aa-442c-af9e-87390b313dc7)
![fs](https://github.com/AnonymouX47/termvisage/assets/56853194/4b17d0a2-225f-4c06-8ff0-242bcf7ef18f)

This particular picture is very large.
```
t@t-MS-7C90:~/Pictures$ ll big-sur-mountains-night-dark-macos-big-sur-stock-california-6016x6016-1493.jpg 
-rw-rw-r-- 1 t t 4,7M Mär 10 13:11 big-sur-mountains-night-dark-macos-big-sur-stock-california-6016x6016-1493.jpg
t@t-MS-7C90:~/Pictures$ exif big-sur-mountains-night-dark-macos-big-sur-stock-california-6016x6016-1493.jpg 
EXIF tags in 'big-sur-mountains-night-dark-macos-big-sur-stock-california-6016x6016-1493.jpg' ('Motorola' byte order):
--------------------+----------------------------------------------------------
Tag                 |Value
--------------------+----------------------------------------------------------
Orientation         |Top-left
X-Resolution        |72
Y-Resolution        |72
Resolution Unit     |Inch
Software            |Pixelmator 3.9
Date and Time       |2020:06:22 22:06:64
Pixel X Dimension   |6016
Pixel Y Dimension   |6016
Exif Version        |Exif Version 2.1
FlashPixVersion     |FlashPix Version 1.0
Color Space         |Uncalibrated
--------------------+----------------------------------------------------------
```

**Comment by AnonymouX47** [comment]
> The only issue I have now is that one particular picture is not drawn in the preview. If I select it and termvisage goes fullscreen mode it is also not drawn. When I force it to render it is finally drawn.

That's by design, for performance reasons. See [`--max-pixels`](https://termvisage.readthedocs.io/en/latest/cli.html#cmdoption-max-pixels).

**Comment by qrockz** [comment]
Maybe it is worth to look into [allmytoes](https://lib.rs/crates/allmytoes). It can create smaller sized thumbnails and cache them.

**Comment by AnonymouX47** [comment]
Honestly, not a good idea in my opinion (i.e using `allmytoes` specifically)...

1. It can only be used as either a command-line tool or a rust crate. Neither options is reliable or easily workable.
2. Let's assume I found a way to make it work reliably with good performance, it has just too many dependencies.
3. Thumbnails will only work for the grid view.

Anyways, I appreciate the idea.

I'll look into similar python libraries or simply implement the functionality myself using temp files.

Thank so much. :hugging_face:

- - -

As regards the actual issue at hand, I've managed to fix the bug. I'll clean things up and push the changes as soon as I can.

Thanks for your patience.

**Comment by AnonymouX47** [comment]
You can now follow #12 for updates on image grid thumbnail caching.

Thank you 😃.

**Comment by qrockz** [comment]
@AnonymouX47  I've cloned the repo and successfully compiled it but get an error when starting termvisage:
```
termvisage --tui --verbose-log
Session not ended successfully: (builtins.ValueError) too many values to unpack (expected 1)
```
[log.txt](https://github.com/AnonymouX47/termvisage/files/14922865/log.txt)

**Comment by AnonymouX47** [comment]
@qrockz Thanks for the feedback.

I looked into the issue and found out it was due to an incompatibility with `urwid` versions older than 2.4.2, which was introduced by the earlier changes to fix the original issue. I've corrected this now and all urwid versions down to 2.1.2 (never tested anything less) should work fine.

Also, I'll bump the requirements very soon... they're long overdue for an update.

For what it's worth, next time, when installing from source (except its for the purpose of contribution), I'd advice installing with:
```shell
# `pip` also works but `pipx` is preferable.
pipx install .
```
as the `requirements.txt` file doesn't always (in fact, rarely does) specify the latest versions of dependencies and it also specifies other packages required only for development such as linters, etc.

Thank you 😃.

**Comment by qrockz** [comment]
Sorry for bothering you furthermore :eyes: but when I'm installing termvisage with `pipx install termvisage`  now it still installs the "old" version where I get the error `Session not ended successfully: (urwid.widget.widget.WidgetError) Widget <LineSquare selectable box widget <Image selectable box widget>> rendered (30 x 15) canvas when passed size (30, 1)!`

- downgrading urwid as you previously suggested `pipx inject termvisage urwid==2.1.2` would work to fix that 
- or  instead of downgrading urwid I compile your code with your latest changes and can youse one modern urwid version

I'm really, really sorry if I get something fundamentally wrong here.
But after you have made code changes I was wondering how I can get the updated version of termvisage (the release date and version of termivsiage on the release page on github hasn't changed). pipx still installs the older version of termvisage. What other options do I have to get the latest termvisage other than clone and compile it by myself?

Please help me out and tell me what I'm missing. If you get me to understand this I buy you a big cup of  :coffee:

**Comment by AnonymouX47** [comment]
> Sorry for bothering you furthermore 👀

Not at all :laughing:... It's totally okay to ask for help.

> when I'm installing termvisage with `pipx install termvisage` now it still installs the "old" version where I get the error `Session not ended successfully: (urwid.widget.widget.WidgetError) Widget <LineSquare selectable box widget <Image selectable box widget>> rendered (30 x 15) canvas when passed size (30, 1)!`
> 
>   * downgrading urwid as you previously suggested `pipx inject termvisage urwid==2.1.2` would work to fix that
> 
>   * or  instead of downgrading urwid I compile your code with your latest changes and can youse one modern urwid version

That's because I'm yet to make a new release (to either GitHub or PyPI) since I fixed this issue. Only installing from the repository can get the properly working "version" at the moment. As soon as the next release (which will include this fix) is up, I'll make sure to inform you.

> What other options do I have to get the latest termvisage other than clone and compile the repo by myself?

In the mean time, you can install directly from GitHub using:

```shell
# The same also applies to `pip`
pipx install git+https://github.com/AnonymouX47/termvisage.git
```
_For more info, see [this `pipx` docs section](https://pipx.pypa.io/stable/#installing-from-source-control)._

> Please help me out and tell me what I'm missing. If you get me to understand this I buy you a big cup of ☕ I have no deep knowledge of git or python package installers. Just Basic knowledge.

Once again, it's totally okay... we all learn everyday :hugs:. If you have any other feedback or questions, feel free to give or ask them.

Thank you :smiley:.

**Comment by AnonymouX47** [comment]
Hello again!

This is to inform you that [v0.2.0](https://github.com/AnonymouX47/termvisage/releases/tag/v0.2.0) has just been released, containing the fix/enhancement discussed in this issue. :tada:

You can upgrade to the new version by running:

```shell
pipx upgrade termvisage
# OR `pip install --upgrade termvisage`, if that's your installation method.
```
but if you've earlier installed the package from the git repository (remote or local) or some other source, you might need to run:

```shell
# The same also applies to `pip`
pipx install --force termvisage
```

Thanks so much for your report/suggestion, patience and feedback. :handshake: :smiley:
