### ISSUE TITLE
Displaying high-res images in the TUI

### ISSUE THREAD

**Issue by DreamMaoMao** [AnonymouX47/termvisage#12]
**Description**

some picture can show in `termvisage`  but can't show in `termvisage -r`

**To Reproduce**

1. cd ~/Images
2. termvisage yh.jpg
3. termvisage  -r

**Expected behavior**

can't show the same picturn in `termvisage  -r`

**Screenshots**

![swappy-20240408-190118](https://github.com/AnonymouX47/termvisage/assets/30348075/d1fb82ca-a671-42ea-9ceb-c5df6f83f05f)

![swappy-20240408-190131](https://github.com/AnonymouX47/termvisage/assets/30348075/f5f7e555-58e9-4c5a-995d-96cd0477fbf4)

**Desktop (please complete the following information, if applicable):**

- OS: arch
- Kernel version 6.5.7-arch1-1 

**Package info:**

- Python version: Python 3.11.5
- Package version: 0.1.0
- Installation method:pipx

**Terminal Emulator:**

- Name:konsole
- Version:23.08.4

**Additional context**

**Comment by DreamMaoMao** [comment]
you can find the picture in here:

https://github.com/DreamMaoMao/tempcache/blob/main/yh.jpg

**Comment by AnonymouX47** [comment]
See https://github.com/AnonymouX47/termvisage/issues/10#issuecomment-2028897479 and the comments following it.

Like I said in https://github.com/AnonymouX47/termvisage/issues/10#issuecomment-2036007043, I'll look into it and find an efficient way to implement thumbnail caching soon.

Henceforth, this will be the issue tracking support for the feature.

Thank you 😃.

**Comment by AnonymouX47** [comment]
Hello @DreamMaoMao, @qrockz!

I know it's been a while but rest assured, I've been and am still actively working on this.

I've just pushed the initial implementation, which can be seen at #13. Still got a few more (though not trivial :grin:) aspects to implement, majorly thumbnail deduplication :yum:. You can test it out by installing with:
```shell
# `pip` also works.
pipx install git+https://github.com/AnonymouX47/termvisage.git@rendering
```
_**NOTE**: Since you already have it installed, you might need to uninstall that version (via `pipx uninstall termvisage`) first._

I'll greatly appreciate your feedback. :pray:

Thank you for your patience. :smiley:

**Comment by DreamMaoMao** [comment]
It can display the small preview image but after pressing enter some images will not be displayed, such as the image I mentioned above

**Comment by qrockz** [comment]
Large picture shows up in thumpnail mode. 
![1](https://github.com/AnonymouX47/termvisage/assets/56853194/9abc2812-848b-4265-b9e0-d32f79de6d6c) 

Selecting and hitting enter to open it produces just jibberish.
![2](https://github.com/AnonymouX47/termvisage/assets/56853194/45858f24-3522-478a-965f-0c123af4c110)

**Comment by AnonymouX47** [comment]
You're both right.

Once again (was briefly addressed earlier [here](https://github.com/AnonymouX47/termvisage/issues/10#issuecomment-2028899251)), the reason for this behaviour is to improve **performance**.

What's happening is, the application refuses to render any image having more pixels than the value of [`max pixels`](https://termvisage.readthedocs.io/en/latest/config.html#confval-max-pixels) (or [`--max-pixels`](https://termvisage.readthedocs.io/en/latest/cli.html#cmdoption-max-pixels), if specified). Instead, it displays a bunch of **exclamation marks (!)** (not actually _gibberish_ :grinning::hugs:). The user can then choose to force the image to be rendered using the "Force Render" action, triggered by `shift + f` (by default), as shown in the image below.

![Screenshot_2024-04-27_22-59-26](https://github.com/AnonymouX47/termvisage/assets/61663146/be4301f3-fd68-4fdd-b742-595ab1bea5cd)

**Anyways**, if you're confident of your device's processing power and prefer that all images be rendered normally (without having to force it), you can simply set the [`max pixels`](https://termvisage.readthedocs.io/en/latest/config.html#confval-max-pixels) config option to an arbitrarily large value. For what it's worth, I've also increased the value of this config option on my main device, to something I'm sure the device can handle well.

<details>
<summary>In more detail...</summary>

The core issue is that high-resolution images take a longer while to render and currently, only a single thread/subprocess is used to render full-sized image views (i.e any view other than the image grid).

Take for example, a user has a directory filled with high-resolution images. As the user scrolls through the list (not grid) of images, the application tries to render the images. Fortunately, the renderer already knows to skip any image that is not the one currently in view but still, there will most likely be one image already being rendered by the time the user is done scrolling to the desired image and the desired image will not start rendering until the other image is done rendering.

This may not be very noticeable on devices with higher processing power but trust me, it becomes more and more noticeable as processing power decreases. Using multiple threads/subprocesses really wouldn't solve the problem since there could be multiple large images to be rendered in succession.

All these were why I introduced the "max pixels" setting, for which I chose a reasonable (I believe) default based on my tests across various devices with varying processing power. My goal was to ensure a smooth experience out-of-the-box across a wider range of processing power.

</details>

- - -

With all that out of the way...

I've put some more though to it and it seems the "max pixels" setting is mostly handful only in [contexts/views](https://termvisage.readthedocs.io/en/latest/tui.html#contexts) where multiple **full** (non-grid) image views can be scrolled through in **quick** succession, which includes every context/view in which images are shown **except the _full-grid-image_ context** (which is what you've both reported about). I'll exclude the _full-grid-image_ context and test, and if the results turn out to align with my hypothesis, I'll keep the new behaviour.

Also, It now seems obvious to me that this behaviour is worthy of a FAQ entry. I'll work on that too.

Thank you very much. :smiley:

**Comment by qrockz** [comment]
> What's happening is, the application refuses to render any image having more pixels than the value of [max pixels](https://termvisage.readthedocs.io/en/latest/config.html#confval-max-pixels) (or [--max-pixels](https://termvisage.readthedocs.io/en/latest/cli.html#cmdoption-max-pixels), if specified). Instead, it displays a bunch of exclamation marks (!) (not actually gibberish 😀🤗). The user can then choose to force the image to be rendered using the "Force Render" action, triggered by shift + f (by default), as shown in the image below.

When I've decided to open a selected picture I want it to render. I don't want to do an extra "confirmation" to force it to render.
When browsing in thumbnail mode and select a large picture which has too much pixels: the selection border should change it's color (from white to yellow) to give the user a hint that it will take a little longer to render this picture when open it.

**Comment by AnonymouX47** [comment]
Hello!

I've implemented the suggested/discussed changes and a couple more. You can go ahead to test these by following the [earlier instructions](https://github.com/AnonymouX47/termvisage/issues/12#issuecomment-2080415782). As always, I'll appreciate your feedback.

Thank you very much. :smiley:

**Comment by DreamMaoMao** [comment]
it look good to me.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/AnonymouX47/termvisage/assets/30348075/74ef9bc7-3999-4905-9aa9-4dbd9467a636)
The default minimum still seems to be too large. I want to see more images at the same time. Can we allow the user to set the launch picture size?

**Comment by AnonymouX47** [comment]
Oh, interesting!

That's not a problem at all, literally costs me nothing to reduce the lower bound for the [`cell width`](https://termvisage.readthedocs.io/en/latest/config.html#confval-cell-width) config option, which is currently 30 columns. Though, I think I'll still leave the default at 30 columns. :thinking:

What do you think a better minimum would be?... 20 (Tried 10 but everything below 20 didn't look good on my end)?

Once again, it's really interesting and useful having your perspectives. :hugs: Personally, I would never have thought 30 wasn't small enough (I even use 36 as my default). :laughing:

Thanks for your suggestions. :pray:

**Comment by DreamMaoMao** [comment]
It would be nice to have a size that can be reduced to this 

![image](https://github.com/AnonymouX47/termvisage/assets/30348075/63700ee4-4d52-475d-904b-4788124ae746)

**Comment by AnonymouX47** [comment]
I see... I'll go with a minimum of 10 then.

I'll implement this is a new PR once I merge #13, in order to avoid conflicts. Also, they're quite distinct issues.

**Comment by AnonymouX47** [comment]
Hello!
I come bearing good news!! :partying_face:

I believe this issue should've been completely resolved by #13, #15 and #16. It's been a lot (particularly #13 and #16) but I'm glad it's finally done.

You can now install from the `main` branch using:
```shell
# `pip` also works.
pipx install git+https://github.com/AnonymouX47/termvisage.git
```
and let me know if all the issues and suggestions have been resolved, so I can get to release a new version as soon as possible.

For what it's worth... If you have any **new** suggestion (i.e not a direct follow-up to this issue or the changes made to resolve it), I'd prefer you open a new issue.

Thank you very much. :pray:

- - -

@DreamMaoMao, little tip here... If you'll be permanently setting your grid [`cell width`](https://termvisage.readthedocs.io/en/latest/config.html#confval-cell-width) as low as you've suggested, I'd advice you reduce your [`thumbnail size`](https://termvisage.readthedocs.io/en/latest/config.html#confval-thumbnail-size) in order to reduce disk usage and speed up thumbnail generation, since you probably wouldn't actually need as high a thumbnail resolution as the default.

**Comment by DreamMaoMao** [comment]
![image](https://github.com/AnonymouX47/termvisage/assets/30348075/8080e2c9-417f-4171-a48d-29bc8f46ffae)

It works fine, the only problem is that an error is reported when the cell width is 15,10 and 16 are fine.

**Comment by AnonymouX47** [comment]
As the error message (and the [docs](https://termvisage.readthedocs.io/en/latest/config.html#confval-cell-width)) states (*take note of the emphasis*):

> must be an **even** integer ...

This is intentional as the height (lines) is computed as **half** the width (columns). Hence, the  width is required to be **even** in order to avoid **fractional** heights (since that's impossible to achieve on a terminal).

Thank you. :smiley:

**Comment by AnonymouX47** [comment]
Glad it's all been resolved. :smiley:

Thanks for all your suggestions and feedback. :pray:

**Comment by AnonymouX47** [comment]
@ qrockz, any particular feedback about the thumbnail feature?

**Comment by qrockz** [comment]
> @qrockz, any particular feedback about the thumbnail feature?
I like it :)

_Maybe_ future request: adding filesize into the border
![oie_aFIMNy4PpFv2(1)](https://github.com/AnonymouX47/termvisage/assets/56853194/814fbf2c-6d1b-4dd9-8a2d-88de51b0a5ea)

**Comment by AnonymouX47** [comment]
> @AnonymouX47
> I like it :)

Great! :+1:

> _Maybe_ future request: adding filesize into the border

I looked into a couple of image viewers with grid views and this is not typical or even rare. I'm not saying it's bad or I don't want something different from the norm (this whole project already is :grin:), it just feels a little odd. Also, I don't think file size is that much a crucial property of an image to given such an highlight (just a personal opinion).

> Or print this and more information (picture pixel measurements at the bottom frame)

I think I can work with this as it's much closer to the typical and gives room for way more information :thinking:... I'll appreciate it if you can open a new issue requesting this feature so we can track things over there.

*Side note: I also have plans for an info/properties panel or pop-up (prefer the later) that'll contain these details along with other available metadata.*

Thanks so much. :smiley:

**Comment by AnonymouX47** [comment]
Hello again!

This is to inform you that [v0.2.0](https://github.com/AnonymouX47/termvisage/releases/tag/v0.2.0) has just been released, containing the fix/enhancement discussed in this issue. :tada:

You can upgrade to the new version by running:

```shell
pipx upgrade termvisage
# OR `pip install --upgrade termvisage`, if that's your installation method.
```
but if you've earlier installed the package from the git repository (remote or local) or some other source, you might need to run:

```shell
# The same also applies to `pip`
pipx install --force termvisage
```

Thanks so much for your report/suggestion, patience and feedback. :handshake: :smiley:
