### ISSUE TITLE
Pixelated image instead of high resolution with iTerm2.

### ISSUE THREAD

**Issue by ys-2020** [AnonymouX47/termvisage#8]
Hi. Thank you for the amazing work. I am trying to print some images to the iTerm2 terminal. However, by using the default settings, I only get pixelated images instead of high-resolution ones. #7 might be related to this problem but I did not use `tmux`. I am wondering if any one could help! Thanks!

**Description**
Cannot display high resolution image. #7 might be related.

**To Reproduce**
```
pipx install termvisage
wget https://user-images.githubusercontent.com/61663146/235449392-b464ff19-82ac-4c55-9244-e718bc999e98.png
termvisage 235449392-b464ff19-82ac-4c55-9244-e718bc999e98.png
```

**Expected behavior**
Expect to see a high resolution image instead of pixelated image.

**Screenshots**

<img width="943" alt="Screenshot 2024-01-04 at 12 49 27 PM" src="https://github.com/AnonymouX47/termvisage/assets/61508922/51e36dfe-fb18-4046-9400-fa1fac36f634">

**Desktop (please complete the following information, if applicable):**

- OS: Ubuntu
- Version 22.04

**Package info:**

- Python version: 3.9.17
- Package version: 0.1.0
- Installation method: PyPI

**Terminal Emulator:**

- Name: iTerm2
- Version: 3.4.23

**Comment by AnonymouX47** [comment]
Hello! Thanks for the compliments.

1. How could you be running iTerm2 on Ubuntu? :thinking:
2. Please run `echo -e '\e[>q'` within the same terminal and let me know what you see.

**Comment by ys-2020** [comment]
Hi! Thank you very much for the prompt reply! 

Sorry for the unclarity. Actually I am running iterm2 on my Mac and ssh to Ubuntu server. And I am just wondering if there is any possibility to show image on my local terminal while ssh-ing to a remote ubuntu server? 

The `echo -e '\e[>q'` returns `echo -e '\e[>q'>|iTerm2 3.4.23`.
And `echo $TERM_PROGRAM` returns empty outputs.

**Comment by AnonymouX47** [comment]
I see... thanks for the clarification.

Yes, it's possible to display [high-res] images in remote sessions.

From the screenshot and the information you've given, it seems the problem is that the terminal responds late to [**queries**](https://term-image.readthedocs.io/en/latest/guide/concepts.html#terminal-queries) due to the session being remote. The seemingly garbage text at the top-left of the image output in your screenshot is actually a response from the terminal to a query sent by the image viewer... the fact that it shows there means it came in later than the timeout. See **"Why does my program get garbage input (possibly also written to the screen) or phantom keystrokes?"** in the library's [FAQs](https://term-image.readthedocs.io/en/latest/faqs.html#faqs).

To solve the problem, you can increase the timeout (default is `0.1`) using the [`--query-timeout`](https://termvisage.readthedocs.io/en/latest/cli.html#cmdoption-query-timeout) CLI option or the [`query timeout`](https://termvisage.readthedocs.io/en/latest/config.html#confval-query-timeout) config option.

Please, try the suggested solution above and let me know the result.

Thank you.

**Comment by ys-2020** [comment]
I see. Modifying `--query-timeout` seems to work! Thank you so much!

**Comment by AnonymouX47** [comment]
You're welcome.
